services:
  front:
    container_name: heroes-of-eternity_front
    image: oven/bun:slim
    user: bun
    ports:
      - "${DOCKER_FRONT_EXTERNAL_PORT}:8080"
    working_dir: /home/bun/app/apps/front
    volumes:
      - .:/home/bun/app:cached
    command: bun dev
    networks:
      - heroes-of-eternity 

  back:
    container_name: heroes-of-eternity_back
    image: oven/bun:slim
    user: bun
    ports:
      - "${DOCKER_BACK_EXTERNAL_PORT}:3000"
    working_dir: /home/bun/app/apps/back
    volumes:
      - .:/home/bun/app:cached
    command: bun dev
    networks:
      - heroes-of-eternity

  postgres:
    image: postgres:15-alpine
    container_name: heroes-of-eternity_postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - heroes-of-eternity

volumes:
  postgres_data:

networks:
  heroes-of-eternity:
