# Railway configuration

[deploy]
branch = "master"

databases = [
  {
    name = "postgres",
    type = "postgres",
    size = "free"
  }
]

services = [
  {
    name = "backend",
    type = "nodejs",
    port = 3000,
    path = "apps/back",
    env = {
      DATABASE_HOST = "${{PGHOST}}",
      DATABASE_NAME = "${{PGDATABASE}}",
      DATABASE_USER = "${{PGUSER}}",
      DATABASE_PASSWORD = "${{PGPASSWORD}}",
      DATABASE_PORT = "5432",
      NODE_ENV = "production"
    }
  },
  {
    name = "frontend" ,
    type = "nodejs",
    port = 5173,
    path = "apps/front",
    env = {
      PUBLIC_BACK_URL = "http://${{BACKEND_HOST}}:3000",
      NODE_ENV = "production"
    }
  }
]
