# Railway configuration

[deploy]
branch = "master"

databases = [
  {
    name = "postgres",
    type = "postgres",
    size = "free"
  }
]

services = [
  {
    name = "backend",
    type = "nodejs",
    port = 3000,
    path = "apps/back",
    env = {
      DATABASE_HOST = "${{Postgres.PGHOST}}",
      DATABASE_NAME = "${{Postgres.PGDATABASE}}",
      DATABASE_USER = "${{Postgres.PGUSER}}",
      DATABASE_PASSWORD = "${{Postgres.PGPASSWORD}}",
      DATABASE_PORT = "${{Postgres.PGPORT}}",
      NODE_ENV = "production"
    },
    build = {
      builder = "NIXPACKS",
      buildCommand = "bun i && bun run build:deps"
    }
  },
  {
    name = "sockets",
    type = "nodejs",
    port = 3000,
    path = "apps/sockets",
    env = {
      BACKEND_HOST = "${{back.RAILWAY_PRIVATE_DOMAIN}}",
      NODE_ENV = "production"
    },
    build = {
      builder = "NIXPACKS",
      buildCommand = "bun i && bun run build:deps"
    }
  },
  {
    name = "frontend",
    type = "nodejs",
    port = 5173,
    path = "apps/front",
    env = {
      PUBLIC_BACK_URL = "${{back.RAILWAY_PUBLIC_DOMAIN}}",
      PUBLIC_BACK_WS_URL = "${{sockets.RAILWAY_PUBLIC_DOMAIN}}",
      NODE_ENV = "production"
    },
    build = {
      builder = "NIXPACKS",
      buildCommand = "bun i && bun run build:deps && bun run build:front"
    }
  }
]
