name: Backend Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          cache: true
      
      - name: Install dependencies
        run:
          bun install && bun run build:deps && bun install
        
      
      - name: Run tests
        run: cd apps/back && bun test
        env:
          NODE_ENV: test
